/**
 * Machine-readable error codes used across the entire API.
 * Every throw site MUST use one of these codes.
 * Numeric HTTP status lives separately in the response `status` field.
 */
export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_TOKEN_FAMILY_COMPROMISED: 'AUTH_TOKEN_FAMILY_COMPROMISED',
  AUTH_MUST_CHANGE_PASSWORD: 'AUTH_MUST_CHANGE_PASSWORD',
  AUTH_PASSWORD_POLICY: 'AUTH_PASSWORD_POLICY',
  AUTH_INVALID_CURRENT_PASSWORD: 'AUTH_INVALID_CURRENT_PASSWORD',

  // Tests
  TEST_NOT_FOUND: 'TEST_NOT_FOUND',
  TEST_FORBIDDEN: 'TEST_FORBIDDEN',
  TEST_INVALID_TRANSITION: 'TEST_INVALID_TRANSITION',
  TEST_TRANSITION_NOT_ALLOWED_BY_CLIENT: 'TEST_TRANSITION_NOT_ALLOWED_BY_CLIENT',
  TEST_NUMBER_COLLISION: 'TEST_NUMBER_COLLISION',
  TEST_ID_CONFLICT: 'TEST_ID_CONFLICT',
  TEST_NOT_COMPLETED: 'TEST_NOT_COMPLETED',
  TEST_MISSING_CLASSIFICATION: 'TEST_MISSING_CLASSIFICATION',

  // Evidence
  EVIDENCE_NOT_FOUND: 'EVIDENCE_NOT_FOUND',
  EVIDENCE_CHAIN_BROKEN: 'EVIDENCE_CHAIN_BROKEN',
  EVIDENCE_TAMPERING_DETECTED: 'EVIDENCE_TAMPERING_DETECTED',
  EVIDENCE_INVALID_VERSION: 'EVIDENCE_INVALID_VERSION',

  // Image upload
  IMAGE_HASH_MISMATCH: 'IMAGE_HASH_MISMATCH',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  UNSUPPORTED_IMAGE_TYPE: 'UNSUPPORTED_IMAGE_TYPE',
  IMAGE_ALREADY_EXISTS: 'IMAGE_ALREADY_EXISTS',
  IMAGE_CONFLICT: 'IMAGE_CONFLICT',
  INVALID_UPLOAD_PATH: 'INVALID_UPLOAD_PATH',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_EXPIRED: 'UPLOAD_EXPIRED',
  INVALID_IMAGE_URL: 'INVALID_IMAGE_URL',

  // Kit management
  KIT_CREATED: 'KIT_CREATED',
  KIT_UPDATED: 'KIT_UPDATED',
  KIT_DEACTIVATED: 'KIT_DEACTIVATED',
  KIT_VERSION_CREATED: 'KIT_VERSION_CREATED',
  KIT_REAGENT_EXPIRED: 'KIT_REAGENT_EXPIRED',
  READING_WINDOW_VIOLATION: 'READING_WINDOW_VIOLATION',
  INVALID_CONTROL_TEST: 'INVALID_CONTROL_TEST',

  // Case & Sample
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  SAMPLE_NOT_FOUND: 'SAMPLE_NOT_FOUND',
  CUSTODY_EVENT_INVALID: 'CUSTODY_EVENT_INVALID',

  // Review & Lab Confirmation
  REVIEW_IMMUTABLE: 'REVIEW_IMMUTABLE',
  REVIEW_INVALID_STATE: 'REVIEW_INVALID_STATE',
  LAB_CONFIRMATION_EXISTS: 'LAB_CONFIRMATION_EXISTS',

  // Analytics
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',

  // Organization & Tenancy
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  UNIT_NOT_FOUND: 'UNIT_NOT_FOUND',
  CROSS_UNIT_ACCESS_DENIED: 'CROSS_UNIT_ACCESS_DENIED',

  // Signing keys
  SIGNING_KEY_NOT_FOUND: 'SIGNING_KEY_NOT_FOUND',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_CONFLICT: 'USER_EMAIL_CONFLICT',
  USER_OPERATOR_ID_CONFLICT: 'USER_OPERATOR_ID_CONFLICT',

  // ML / integrations
  ML_UNAVAILABLE: 'ML_UNAVAILABLE',
  ML_PROCESSING_FAILED: 'ML_PROCESSING_FAILED',

  // Sync
  SYNC_CONFLICT: 'SYNC_CONFLICT',

  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  APP_VERSION_TOO_OLD: 'APP_VERSION_TOO_OLD',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
